### ISSUE TITLE
Unit Tests

### ISSUE THREAD

**Issue by nickthegroot** [lohs-software-club/LOClubBot#1]
Unit tests to make sure everything works before pushing to the server.

**Comment by MoralCode** [comment]
"before pushing to the server."

its hosted on my pi lol. I have to manually upload.

**Comment by nickthegroot** [comment]
In the future we may want to host on AWS or Azure @DeveloperACE

**Comment by MoralCode** [comment]
@nbd9 would heroku work? I kinda like them. and its free if you have low usage

**Comment by nickthegroot** [comment]
Discussed and thought against. Time better spent fixing other issues. Closing for now.
